name: Docker Deployment

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  push-image:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Image push to registry
      run: ./build.sh
